import type { Lead } from "./types"

// Placeholder data for the Figma migration — statuses use the real
// pipeline_stages names so nothing needs re-labelling when this screen is
// wired to the database.
export const MOCK_LEADS: Lead[] = [
  { id: 'l1', profileId: 'p1', profileName: 'Sarah Chen', jobTitle: 'Senior Frontend Engineer', company: 'Vercel', jobLocation: 'Remote', workType: 'remote', appliedAt: '2026-07-28', status: 'Client Interview', assignedTo: 'u2', bdNotes: 'Strong interest from hiring manager. Technical round scheduled for next week.', salary: '$150k – $185k', parser: 'LinkedIn' },
  { id: 'l2', profileId: 'p2', profileName: 'Marcus Webb', jobTitle: 'Staff Software Engineer', company: 'Linear', jobLocation: 'Remote', workType: 'remote', appliedAt: '2026-07-25', status: 'HR Interview', assignedTo: 'u3', bdNotes: 'Initial call went well. Waiting on recruiter response.', salary: '$200k – $240k', parser: 'Greenhouse' },
  { id: 'l3', profileId: 'p3', profileName: 'Priya Nair', jobTitle: 'Senior Backend Engineer', company: 'Stripe', jobLocation: 'New York, NY', workType: 'hybrid', appliedAt: '2026-07-20', status: 'Tech Interview 1', assignedTo: 'u2', bdNotes: 'Completed phone screen. Technical challenge submitted.', salary: '$160k – $200k', parser: 'LinkedIn' },
  { id: 'l4', profileId: 'p5', profileName: 'Nia Okonkwo', jobTitle: 'Senior React Native Engineer', company: 'Spotify', jobLocation: 'Stockholm', workType: 'hybrid', appliedAt: '2026-07-18', status: 'Offer Received', assignedTo: 'u2', bdNotes: 'Offer received! €125k + equity. Negotiation in progress.', salary: '€110k – €140k', parser: 'LinkedIn' },
  { id: 'l5', profileId: 'p1', profileName: 'Sarah Chen', jobTitle: 'Engineering Manager – Frontend', company: 'Figma', jobLocation: 'San Francisco', workType: 'hybrid', appliedAt: '2026-07-15', status: 'Applied', assignedTo: 'u3', bdNotes: '', salary: '$220k – $270k', parser: 'Greenhouse' },
  { id: 'l6', profileId: 'p2', profileName: 'Marcus Webb', jobTitle: 'Principal Engineer – Platform', company: 'Shopify', jobLocation: 'Remote', workType: 'remote', appliedAt: '2026-07-10', status: 'Closed', assignedTo: 'u2', bdNotes: 'Position filled internally.', salary: 'CAD $220k – $280k', parser: 'Workday' },
  { id: 'l7', profileId: 'p4', profileName: 'Jordan Kim', jobTitle: 'Principal Infrastructure Engineer', company: 'Cloudflare', jobLocation: 'Remote', workType: 'remote', appliedAt: '2026-08-01', status: 'Assessment Submitted', assignedTo: 'u3', bdNotes: 'Very strong match on Rust + distributed systems.', salary: '$210k – $260k', parser: 'Lever' },
  { id: 'l8', profileId: 'p3', profileName: 'Priya Nair', jobTitle: 'ML Infrastructure Engineer', company: 'Anthropic', jobLocation: 'San Francisco', workType: 'onsite', appliedAt: '2026-08-02', status: 'Assessment Received', assignedTo: 'u3', bdNotes: '', salary: '$180k – $220k', parser: 'Indeed' },
  { id: 'l9', profileId: 'p5', profileName: 'Nia Okonkwo', jobTitle: 'Mobile Platform Lead', company: 'Duolingo', jobLocation: 'Pittsburgh, PA', workType: 'hybrid', appliedAt: '2026-07-05', status: 'Offer Accepted/Rejected', assignedTo: 'u2', bdNotes: 'Offer declined — candidate accepted a competing role.', salary: '$190k – $230k', parser: 'Greenhouse' },
  { id: 'l10', profileId: 'p4', profileName: 'Jordan Kim', jobTitle: 'Staff Platform Engineer', company: 'Datadog', jobLocation: 'Remote', workType: 'remote', appliedAt: '2026-08-03', status: 'Tech Interview 2', assignedTo: 'u3', bdNotes: 'Second technical round booked for Friday.', salary: '$200k – $250k', parser: 'Lever' },
]
