#!/usr/bin/env node
// Creates the Recurso Labs Admin auth user (SQL seed files cannot create
// auth.users rows). No profile is created or linked — profiles are a
// separate, unrelated concept from users.
//
// Usage:
//   node scripts/createUser.cjs
//   npm run seed:user
//
// Prereqs:
//   1. Migrations applied (npm run migrate:up).
//   2. supabase/seed.sql applied (creates the Recurso Labs organization and
//      the Admin role this script looks up).

// eslint-disable-next-line @typescript-eslint/no-require-imports
require('dotenv').config({ path: '.env.local' });
// eslint-disable-next-line @typescript-eslint/no-require-imports
const { createClient } = require('@supabase/supabase-js');

const ADMIN_EMAIL = 'fareed.zafar@recursolabs.com';
const ADMIN_PASSWORD = 'Test@123';
const ADMIN_NAME = 'Fareed Zafar';
const ORG_NAME = 'Recurso Labs';
const ROLE_NAME = 'Admin';

async function main() {
  const url = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SECRET_KEY || process.env.SUPABASE_SERVICE_ROLE_KEY;
  if (!url || !serviceKey) {
    console.error('Missing NEXT_PUBLIC_SUPABASE_URL and SUPABASE_SECRET_KEY (or SUPABASE_SERVICE_ROLE_KEY) in .env.local');
    process.exit(1);
  }

  const supabase = createClient(url, serviceKey, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  // 0) Resolve the organization (UUIDs are generated by the DB — never hardcode)
  const { data: org, error: orgErr } = await supabase
    .from('organizations')
    .select('id, name')
    .eq('name', ORG_NAME)
    .is('deleted_at', null)
    .limit(1)
    .single();
  if (orgErr || !org) {
    console.error(`No organization named '${ORG_NAME}' found.`, orgErr?.message || '');
    console.error('Apply supabase/seed.sql first (e.g. `supabase db reset`) so the organization and roles exist.');
    process.exit(1);
  }

  // 1) Resolve the Admin role
  const { data: roleRow, error: roleErr } = await supabase
    .from('roles')
    .select('id, name')
    .eq('name', ROLE_NAME)
    .maybeSingle();
  if (roleErr) {
    console.error('roles lookup error:', roleErr.message);
    process.exit(1);
  }
  if (!roleRow) {
    console.error(
      `Role '${ROLE_NAME}' not found. Apply supabase/seed.sql first — users.role_id is NOT NULL, so the user cannot be created without it.`
    );
    process.exit(1);
  }

  // 2) Auth user (idempotent: reuse if the email already exists)
  let userId;
  const { data: created, error: createErr } = await supabase.auth.admin.createUser({
    email: ADMIN_EMAIL,
    password: ADMIN_PASSWORD,
    email_confirm: true,
    user_metadata: { full_name: ADMIN_NAME },
  });
  if (createErr) {
    if (/already.*registered|already been registered/i.test(createErr.message)) {
      console.warn('Auth user already exists, looking it up...');
      const { data: list, error: listErr } = await supabase.auth.admin.listUsers();
      if (listErr) {
        console.error('Could not list users:', listErr.message);
        process.exit(1);
      }
      const existing = list.users.find((u) => u.email?.toLowerCase() === ADMIN_EMAIL.toLowerCase());
      if (!existing) {
        console.error('Auth user reported as existing but not found in listUsers.');
        process.exit(1);
      }
      userId = existing.id;
    } else {
      console.error('Auth createUser error:', createErr.message);
      process.exit(1);
    }
  } else {
    userId = created.user?.id;
  }

  if (!userId) {
    console.error('No user ID resolved');
    process.exit(1);
  }

  // 3) public.users row (id = auth user id, FK enforced). Id is the auth
  // user's own (already a real UUID from Supabase Auth) — nothing here is
  // hardcoded.
  const { error: usersErr } = await supabase
    .from('users')
    .upsert(
      {
        id: userId,
        organization_id: org.id,
        role_id: roleRow.id,
        full_name: ADMIN_NAME,
        email: ADMIN_EMAIL,
        is_active: true,
      },
      { onConflict: 'id' }
    );
  if (usersErr) {
    console.error('users upsert error:', usersErr.message);
    process.exit(1);
  }

  console.log('\n✅ Admin user ready:');
  console.log('   Email:   ', ADMIN_EMAIL);
  console.log('   Password:', ADMIN_PASSWORD);
  console.log('   Name:    ', ADMIN_NAME);
  console.log('   Role:    ', roleRow.name);
  console.log('   Org:     ', org.name);
  console.log('\nYou can now log in through the app.');
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
